site_name: Alessandro Siletto

nav:
    - Home: index.md
    - IT:
      - IT/kubernetes-homelab.md
    - Acquario:
      - acquario/riproduzione-caridina-multidentata.md
    - Intelligenza Artificiale:
      - AI/coding-in-the-AI-era.md
    - Knowledge Base: knowledge-base/index.md

theme:
  name: simple-blog
  favicon: assets/favicon.ico
#  logo: assets/logo.png
  theme_style: light
  site_name_style: bold
  title_style: bold
  sidebar: true
  navigation_depth: 2
  highlightjs: true
    - yaml
    - python
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: false
    menu: true
    preview: true
    footer: false

plugins:
  - macros

extra_css:
  - assets/knowledge-base.css

extra_javascript:
 - assets/custom.js
